// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DataAccessLayer.Models;

public partial class Room : BaseEntity
{
    public string Name { get; set; }

    public int Rating { get; set; }

    public string Description { get; set; }

    public string Length { get; set; }

    public string Width { get; set; }

    public Guid HouseId { get; set; }

    public string Services { get; set; }

    public virtual House House { get; set; }

    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();

    public virtual ICollection<Rating> Ratings { get; set; } = new List<Rating>();
}